### ISSUE TITLE
Wordpress: perform all replacements inside the "Replace" step

### ISSUE THREAD

**Issue by tampe125** [akeeba/angie#28]
Currently we are doing some basic replacements while saving the configuration file.
This means that the **Replacement** step is going to work on some strings that are already up to date. 
This is conceptually wrong and in some cases it could cause issues: for example if the new site is in a folder that contains the old one (ie `www.example.com/asd` => `www.example.com/asdd`) the `asd` string will be replaced twice, resulting in a broken site.

Most likely this is a leftover of our initial attempt to perform some basic replacements on the data saved inside the database, now we have to move everything inside the real **Replacement**  step.

**Comment by tampe125** [comment]
@nikosdion I think we're stuck with an issue here. Even after moving everything inside the Replacement step, we had the same issue. The main reason here is that even our default replacements overlaps:

```
/Applications/MAMP/htdocs/wordpress
http://localhost/wordpress
/wordpress
\/Applications\/MAMP\/htdocs\/wordpress
http:\/\/localhost\/wordpress
\/wordpress
```

As you can see, when we try to replace the third element (`/wordpress`) it will clash with the first and second one. I _could_ change the order and start from the less significant one (`/wordpress`) and move to the longest one (`/Applications/MAMP/htdocs/wordpress`), however I'm afraid we could miss some entries.

What about adding a warning and tell the user to change the folder name? At the end of the day this will happen very few time, there's no need to change the whole logic for some edgy cases.

**Comment by nikosdion** [comment]
You are wrong. Since all replacements run serially on each piece of data it makes sense that we go from UNescaped to escaped. For example, if I have the old path /foobar then the
`/foobar` to `/wordpress`
will run before
`/\foobar` to `/\wordpress`
This is GREAT because if I have `/\foobar` it will be converted by the FIRST rule to `/\wordpress` and the second rule will NOT match anything. Do not change the order they are listed! They are listed like that for a good reason. I had already thought of the overlap.

The most important thing we MUST address is the edge case of our user. I told you yesterday.

WHEN:
* the site URL **before** the path is the same as the old site URL **before** the path; AND
* the new site URL's _path_ starts with the old site URL's _path_ (i.e. the new is a superset of the old one)
THEN:
* MOVE add the unescaped and escaped old path to new path translations in the list (items 3 and 6 in your example) on spot up.

This means that the order FOR THIS PARTICULAR CASE ONLY would be
```
/Applications/MAMP/htdocs/wordpress
/wordpress
http://localhost/wordpress
\/Applications\/MAMP\/htdocs\/wordpress
\/wordpress
http:\/\/localhost\/wordpress
```

The reason is, again, the order of operations. Since the NEW path is a superset of the OLD path the 3rd and 6th replacements will match what has already been replaced by the 2nd and 5th replacements. 

*THIS ONLY HAPPENS BECAUSE THE NEW PATH IS A SUPERSET OF THE OLD PATH* e.g. New Path = `/foobar` when Old Path = `/foo`. The 2nd replacement would convert `http://localhost/foo` to `http://localhost/foobar`. The third replacement would then match the SAME `/foo` resulting in `http://localhost/foobarbar`. That's why in this extreme case the 3rd and 6th replacements must be reversed.

**Comment by tampe125** [comment]
Small heads up. Even using the inverted order, we still have the same issue. This is what happens:

**Original value**: http://localhost/wordpress
**Applied change**: /wordpress => /wordpresss
**New value**: http://localhost/wordpresss

**Original value**: http://localhost/wordpresss
**Applied change**: http://localhost/wordpress => http://localhost/wordpresss
**New value**: http://localhost/wordpressss

I'll try setting up virtual domains but I'm afraid we're on a slippery slope

**Comment by nikosdion** [comment]
Not really :) The second replacement is a tautology. You are replacing `http://localhost/wordpresss` with itself (`http://localhost/wordpresss`). Unless you meant something different?

**Comment by tampe125** [comment]
Count the `s` ;)
Inside the `http://localhost/wordpresss` string, we are going to replace the part `http://localhost/wordpress` with `http://localhost/wordpresss`. So the `s` at the end are 4.

**Comment by nikosdion** [comment]
OK, we need to do ONE MORE THING.

We MUST NOT replace the entire old URL with the new URL. Instead we should replace the old URL up to but not including the path with the new URL up to but not including the path. Example:
*Old URL*: https://www.example.com/foo
*New URL*: http://localhost/foobar
You need to replace `https://www.example.com/` with `http://localhost/`.

That does half of the job. The other half is the path replacement: `/foo` to `/foobar`

Now the order is irrelevant. Also, it's not a special case anymore, it's the standard way to handle all sites. Also, in the interest of efficiency, do NOT add the following replacements to the list we present to the users:
* Old domain to new domain if the protocol, domain and port is the same
* Old path to new path if they are the same
* Old absolute directory to new absolute directory if they are the same
Also, if the data replacement is submitted with a completely empty replacements mapping (i.e. we are restoring on the same server) then simply don't do anything. Just mark the process as finished right away. These changes work around the problem of failed restorations to the same location on shit hosts.

One stone, two birds. How do you like *that*? 😆
