### ISSUE TITLE
WordPress: Handle WordFence configuration

### ISSUE THREAD

**Issue by tampe125** [akeeba/angie#38]
When WordFence is used in autoprepend mode, it will create a custom PHP configuration file and add the absolute path to their script.  
This means that when they move to a new server, things will break.  
We should inform the user that they should replace or delete the custom PHP configuration file using ANGIE builtin feature.

**Comment by nikosdion** [comment]
Ideally we should show that on the Site Setup page where they can enable said built-in feature :)

**Comment by tampe125** [comment]
FYI I spent some time and this and I decided that the best thing to do is to simply "deactivate" such feature by putting a `return` statement at the top of the file.
We can't delete the file since it would be required by the `.htaccess`/`php.ini`/`user.ini` configuration file, and their configuration changes by server to server; fiddling with such files is something I'd really wish to avoid, since it could break the site.
Once "disabled", the user can simply get inside WordFence and re-enable it: such plugin will regenerate the code with the correct params.

**Comment by nikosdion** [comment]
For starters, I want this to **only happen when restoring the site to a different URL or absolute path**. If they are restoring the site to the same URL **and** absolute filesystem path we must NOT deactivate the WordFence protection.

If we have to disable the WordFence protection I want us to show a warning in the Site Setup page explaining that we are deactivating the plugin because you are restoring to a different server, domain name or disk location; if we didn't disable the plugin the restored site would not be able to load. Moreover, I want us to show the same warning PLUS instructions on reactivating the plugin in the final page of the restoration.
